name: CI
on:
  pull_request:
    paths:
      - "**.swift"
      - .github/workflows/ci.yml
  # schedule:
  #   - cron: "3 3 * * 0" # 3:03 AM, every Sunday
  workflow_dispatch:
jobs:
  macOS:
    runs-on: ${{ matrix.cfg.macos }}
    strategy:
      matrix:
        cfg:
          - swift: "5.6"
            macos: macos-12
          - swift: "5.7"
            macos: macos-12
          - swift: "5.8"
            macos: macos-13
          - swift: "5.9"
            macos: macos-13
          - swift: "5.10"
            macos: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: mxcl/xcodebuild@v3.0.0
        with:
          swift: ${{ matrix.cfg.swift }}
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - swift: "5.2"
            image_suffix: -focal
          - swift: "5.3"
            image_suffix: -focal
          - swift: "5.4"
            image_suffix: -focal
          - swift: "5.5"
            image_suffix: -focal
          - swift: "5.6"
            image_suffix: -focal
          - swift: "5.7"
          - swift: "5.8"
          - swift: "5.9"
          - swift: "5.10"
    container:
      image: swift:${{ matrix.cfg.swift }}${{ matrix.cfg.image_suffix }}
    steps:
      - uses: actions/checkout@v4
      - run: swift test -Xswiftc -suppress-warnings --enable-test-discovery
